### PR TITLE
Use call counter instead of stack trace

### LINKED ISSUE #1: Performance boost
Turns out, that the stack trace creation is indeed relatively expensive (~0.2ms in Chrome on my MacBook Pro). It happens on every call to `memo()`.

Find the pull request for the intended change here: #3

Original PR: #2
See below.

---

## Solution

Instead of matching call site to memoized value by stack trace creation, we should do it like this:

- Create a counter (just a number var) for every call to `useInlineMemo()`
- On call to `memo()`:
  - Replace the call site as a key to a memoized value with the current counter value
  - Increment counter

This way we also map every call to `memo()` to a memoized value, but based upon the order of the `memo()` calls, not based on the call site location.

## Limitations

Conditionally executed code blocks using `memo()` will cause memoized values of later calls to be invalidated if the code block was run before and then is not anymore or was not run before and is now.

#### Example

```js
function MyComponent(props) {
  const memo = useInlineMemo()

  if (props.disabled) {
    return <div style={memo({ opacity: 0.5 }, [])}>Disabled</div>
  }

  return (
    <button onClick={memo(() => props.onStateChange(true))}>Do stuff</button>
  )
}
```

If `props.disabled` switches to `true`, it will invalidate the memoized value of the onClick handler, as the style memo now occupies the counter value that the onClick memo used to have.

Similarly, if `props.disabled` becomes `false`, it will invalidate the memoized value of style/onClick once more.

#### Impact of that limitation

**Might not be an issue in most real-world use cases as state changes that cause conditional code blocks to change behavior will frequently cause major DOM updates for this component. Losing memoized values could be acceptable, as a lot of expensive reconciliation has to be done anyway.**

Best case scenario: The loss of memoized values as a result of conditional code and state changes does not have any performance impact at all as oftentimes the lost values refer to elements that are about to be unmounted.

### PR DESCRIPTION
**Pull request by andywer**
Closes #1.

Preliminary result: 100x faster than the previous implementation (!)

### CODE REVIEW

**Comment by just-boris** [comment]
How will this work with the following code?

```jsx
function Demo() {
   const [count, setCount] = React.useState(0)
   const memo = useInlineMemo();

   if(isDecrementing) {
      return <button onClick={memo(() => setCount(count - 1), [count])}>Decrement</button>
   } else {
      return <button onClick={memo(() => setCount(count + 1), [count])}>Increment</button>
   }
}
```

As far as I can tell, this change will make conditional usage no longer working – which was the primary difference comparing to the original `useCallback` hook

**Comment by andywer** [comment]
Hey @just-boris, thanks for sharing your thoughts!

I feel a bit stupid right now for not foreseeing the obvious issue with use case, tbh... 😕
Damn Sunday quick-fixes.

This is a blocker and it feels like there won't be a solution without a different API.
Any ideas are welcome...

**Comment by andywer** [comment]
Possible new API that is not quite as elegant, but avoids the performance issues and the limitations at the same time:

```js
function Demo() {
   const [count, setCount] = React.useState(0)
   const [memoInc, memoDec] = useInlineMemos()

   if (isDecrementing) {
      return <button onClick={memoInc(() => setCount(count - 1), [count])}>Decrement</button>
   } else {
      return <button onClick={memoDec(() => setCount(count + 1), [count])}>Increment</button>
   }
}
```

What do you think? Is it too inelegant?

The clue is that `useInlineMemo()` would be a generator, yielding any number of memoization functions, as required by the size of the array destructuring assignment.

**Comment by Anber** [comment]
Instead of generating many memo-functions, you can pass a counter ID as an optional third argument. If the argument is omitted, it can be auto-generated by simple babel plugin.

**Comment by Anber** [comment]
Anyway, any solution with counters will cause a lot of hard-to-detect bugs.

**Comment by andywer** [comment]
> Anyway, any solution with counters will cause a lot of hard-to-detect bugs.

True. But the multi-memo-function approach would be fine, as we would always create the same functions at the top, independent from which ones will be run or in which order.

Of course we could also pass an identification parameter manually, but doesn't the array-destructuring approach look cleaner then?

Another option would of course be focussing on usage with a Babel plugin as you said and let it handle the `memo()` call identification statically.

**Comment by andywer** [comment]
I wrapped-up our options in the corresponding issue. See here: <https://github.com/andywer/use-inline-memo/issues/1#issuecomment-522454535>

Let's discuss it there.

**Comment by andywer** [comment]
See #3 instead.

**Pull request closed without merging**
